<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Artists\Add\" />
    <Folder Include="Artists\Delete\" />
    <Folder Include="Artists\Rename\" />
    <Folder Include="Histories\Clear\" />
    <Folder Include="Histories\List\" />
    <Folder Include="Histories\Models\" />
    <Folder Include="Histories\SetLimit\" />
    <Folder Include="Musics\Import\" />
    <Folder Include="Musics\Delete\" />
    <Folder Include="Musics\List\" />
    <Folder Include="Musics\Rename\" />
    <Folder Include="Pictures\Import\" />
    <Folder Include="Pictures\Delete\" />
    <Folder Include="Players\JumpTo\" />
    <Folder Include="Players\Previous\" />
    <Folder Include="Players\SetPlaybackState\" />
    <Folder Include="Players\SetVolume\" />
    <Folder Include="PlaylistMusics\Models\" />
    <Folder Include="PlaylistMusics\List\" />
    <Folder Include="PlaylistMusics\SetOrder\" />
    <Folder Include="Playlists\Models\" />
    <Folder Include="Playlists\List\" />
    <Folder Include="Playlists\Create\" />
    <Folder Include="PlaylistMusics\Add\" />
    <Folder Include="PlaylistMusics\Remove\" />
    <Folder Include="Playlists\Rename\" />
    <Folder Include="Queues\Insert\" />
    <Folder Include="Queues\Clear\" />
    <Folder Include="Queues\Ordering\" />
    <Folder Include="Queues\Shuffle\" />
    <Folder Include="Queues\Remove\" />
    <Folder Include="Thumbnails\Import\" />
    <Folder Include="Thumbnails\Delete\" />
  </ItemGroup>

</Project>
